require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project_tables", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProjectTable. As you add validations to ProjectTable, be sure to
  # adjust the attributes here as well.
  # let(:valid_attributes) {
  #   skip("Add a hash of attributes valid for your model")
  # }

  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }

  # describe "GET /index" do
  #   it "renders a successful response" do
  #     ProjectTable.create! valid_attributes
  #     get project_tables_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /show" do
  #   it "renders a successful response" do
  #     project_table = ProjectTable.create! valid_attributes
  #     get project_table_url(project_table)
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_project_table_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /edit" do
  #   it "renders a successful response" do
  #     project_table = ProjectTable.create! valid_attributes
  #     get edit_project_table_url(project_table)
  #     expect(response).to be_successful
  #   end
  # end

  # describe "POST /create" do
  #   context "with valid parameters" do
  #     it "creates a new ProjectTable" do
  #       expect {
  #         post project_tables_url, params: { project_table: valid_attributes }
  #       }.to change(ProjectTable, :count).by(1)
  #     end

  #     it "redirects to the created project_table" do
  #       post project_tables_url, params: { project_table: valid_attributes }
  #       expect(response).to redirect_to(project_table_url(ProjectTable.last))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "does not create a new ProjectTable" do
  #       expect {
  #         post project_tables_url, params: { project_table: invalid_attributes }
  #       }.to change(ProjectTable, :count).by(0)
  #     end

  #     it "renders a successful response (i.e. to display the 'new' template)" do
  #       post project_tables_url, params: { project_table: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end

  # describe "PATCH /update" do
  #   context "with valid parameters" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested project_table" do
  #       project_table = ProjectTable.create! valid_attributes
  #       patch project_table_url(project_table), params: { project_table: new_attributes }
  #       project_table.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "redirects to the project_table" do
  #       project_table = ProjectTable.create! valid_attributes
  #       patch project_table_url(project_table), params: { project_table: new_attributes }
  #       project_table.reload
  #       expect(response).to redirect_to(project_table_url(project_table))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "renders a successful response (i.e. to display the 'edit' template)" do
  #       project_table = ProjectTable.create! valid_attributes
  #       patch project_table_url(project_table), params: { project_table: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end

  # describe "DELETE /destroy" do
  #   it "destroys the requested project_table" do
  #     project_table = ProjectTable.create! valid_attributes
  #     expect {
  #       delete project_table_url(project_table)
  #     }.to change(ProjectTable, :count).by(-1)
  #   end

  #   it "redirects to the project_tables list" do
  #     project_table = ProjectTable.create! valid_attributes
  #     delete project_table_url(project_table)
  #     expect(response).to redirect_to(project_tables_url)
  #   end
  # end
end
