require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/usertables", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Usertable. As you add validations to Usertable, be sure to
  # adjust the attributes here as well.
  # let(:valid_attributes) {
  #   skip("Add a hash of attributes valid for your model")
  # }

  # let(:invalid_attributes) {
  #   skip("Add a hash of attributes invalid for your model")
  # }

  # describe "GET /index" do
  #   it "renders a successful response" do
  #     Usertable.create! valid_attributes
  #     get usertables_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /show" do
  #   it "renders a successful response" do
  #     usertable = Usertable.create! valid_attributes
  #     get usertable_url(usertable)
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_usertable_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /edit" do
  #   it "renders a successful response" do
  #     usertable = Usertable.create! valid_attributes
  #     get edit_usertable_url(usertable)
  #     expect(response).to be_successful
  #   end
  # end

  # describe "POST /create" do
  #   context "with valid parameters" do
  #     it "creates a new Usertable" do
  #       expect {
  #         post usertables_url, params: { usertable: valid_attributes }
  #       }.to change(Usertable, :count).by(1)
  #     end

  #     it "redirects to the created usertable" do
  #       post usertables_url, params: { usertable: valid_attributes }
  #       expect(response).to redirect_to(usertable_url(Usertable.last))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "does not create a new Usertable" do
  #       expect {
  #         post usertables_url, params: { usertable: invalid_attributes }
  #       }.to change(Usertable, :count).by(0)
  #     end

  #     it "renders a successful response (i.e. to display the 'new' template)" do
  #       post usertables_url, params: { usertable: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end

  # describe "PATCH /update" do
  #   context "with valid parameters" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested usertable" do
  #       usertable = Usertable.create! valid_attributes
  #       patch usertable_url(usertable), params: { usertable: new_attributes }
  #       usertable.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "redirects to the usertable" do
  #       usertable = Usertable.create! valid_attributes
  #       patch usertable_url(usertable), params: { usertable: new_attributes }
  #       usertable.reload
  #       expect(response).to redirect_to(usertable_url(usertable))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "renders a successful response (i.e. to display the 'edit' template)" do
  #       usertable = Usertable.create! valid_attributes
  #       patch usertable_url(usertable), params: { usertable: invalid_attributes }
  #       expect(response).to be_successful
  #     end
  #   end
  # end

  # describe "DELETE /destroy" do
  #   it "destroys the requested usertable" do
  #     usertable = Usertable.create! valid_attributes
  #     expect {
  #       delete usertable_url(usertable)
  #     }.to change(Usertable, :count).by(-1)
  #   end

  #   it "redirects to the usertables list" do
  #     usertable = Usertable.create! valid_attributes
  #     delete usertable_url(usertable)
  #     expect(response).to redirect_to(usertables_url)
  #   end
  # end
end
